name: io_extended_gdglapaz
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  timeline_list: ^0.0.3
  sqflite:
  path_provider:
  #google_sign_in: ^4.0.1+3
  #firebase_auth: ^0.8.3
  #cached_network_image: ^0.8.0
  #shared_preferences: ^0.5.2+1
  url_launcher: ^5.0.2
  qrcode_reader:

dev_dependencies:
  flutter_launcher_icons: ^0.7.2

  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/DEVFEST2019.db
    - assets/img/io_ext_lapaz.png
    - assets/img/gdglapaz_square.png
    - assets/img/twitter.png
    - assets/img/lunch.png
    - assets/img/codelabs.png
    - assets/img/techtalks.png
    - assets/img/gdelogo.jpeg
    - assets/img/speakers/comtec.png
    - assets/img/speakers/jalasoft.png
    - assets/img/speakers/AdrianaM.jpeg
    - assets/img/speakers/ArgelB.jpeg
    - assets/img/speakers/DiegoV.jpg
    - assets/img/speakers/FernandaO.jpg
    - assets/img/speakers/KenjiK.jpg
    - assets/img/speakers/LeonidasE.jpg
    - assets/img/speakers/LuisA.png
    - assets/img/speakers/NoeB.jpg
    - assets/img/speakers/PabloP.jpg
    - assets/img/speakers/VictorA.jpeg
    - assets/img/speakers/YuryC.png
    - assets/img/speakers/summit_global.png
    - assets/img/prizes/gorraTech.png
    - assets/img/prizes/polera.png
    - assets/img/prizes/stkAngular.png
    - assets/img/prizes/stkCloud.png
    - assets/img/prizes/stkDash.png
    - assets/img/prizes/stkDino.png
    - assets/img/prizes/stkFirebase.png
    - assets/img/prizes/stkTensorflow.png
    - assets/img/sponsors/comtec.png
    - assets/img/sponsors/datec.png
    - assets/img/sponsors/jalasoft.png
    - assets/img/sponsors/kaspersky.jpeg
    - assets/img/sponsors/piu.png
    - assets/img/sponsors/ucb.png
    - assets/img/sponsors/mpd.png
    - assets/img/coin.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
